#!/bin/bash

CMAKE_BUILD_TYPE=$1
IVANTK_SOURCE_DIR=$2
IVANTK_BUILD_DIR=$3
ITK_BUILD_DIR=$4
VTK_BUILD_DIR=$5
BUILD_TOOL_OPTIONS=$6

CMAKE_ARGS=" \
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
    -DITK_DIR:PATH=${ITK_BUILD_DIR} \
    -DVTK_DIR:PATH=${VTK_BUILD_DIR} \
    -DIVAN_BUILD_SHARED_LIBS:BOOL=ON \
    -S ${IVANTK_SOURCE_DIR} \
    -B ${IVANTK_BUILD_DIR} \
    "

echo "CMAKE_ARGS=${CMAKE_ARGS}"

# Configure, generate, and build
cmake ${CMAKE_ARGS}
cmake --build ${IVANTK_BUILD_DIR} -- ${BUILD_TOOL_OPTIONS}
