#!/bin/bash

CMAKE_BUILD_TYPE=$1
CAPLIB_LINKAGE=$2
CMAKE_BUILD_PARALLEL_LEVEL=$3
CAPLIB_SOLO_SOURCE_DIR=$4
CAPLIB_BUILD_DIR=$5
VTK_BUILD_DIR=$6
ITK_BUILD_DIR=$7
DCMTK_BUILD_DIR=$8
DCMTK_LIB_DIR=$9
BOOST_BUILD_DIR=${10}
IVANTK_BUILD_DIR=${11}
EVServer_SOURCE_DIR=${12}
EVServer_BUILD_DIR=${13}
BUILD_TOOL_OPTIONS=${14}

# Note that CMAKE_BUILD_TYPE variable is ignored by IDEs

CMAKE_ARGS=" \
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE} \
    -DCMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL} \
    -DExternal_VTK_DIR:PATH=${VTK_BUILD_DIR} \
    -DExternal_ITK_DIR:PATH=${ITK_BUILD_DIR} \
    -DExternal_DCMTK_DIR:PATH=${DCMTK_BUILD_DIR} \
    -DExternal_DCMTK_LIB_DIR:PATH=${DCMTK_LIB_DIR} \
    -DExternal_BOOST_BUILD_DIR:PATH=${BOOST_BUILD_DIR} \
    -DExternal_IVANTK_DIR:PATH=${IVANTK_BUILD_DIR} \
    -DITK_DIR:PATH=${ITK_BUILD_DIR} \
    -DEVServer_SOURCE_DIR:PATH=${EVServer_SOURCE_DIR} \
    -DEVServer_BUILD_DIR:PATH=${EVServer_BUILD_DIR} \
    -DCAPLIB_LINKAGE:STRING=${CAPLIB_LINKAGE} \
    -S ${CAPLIB_SOLO_SOURCE_DIR} \
    -B ${CAPLIB_BUILD_DIR} \
    "

echo "CMAKE_ARGS=${CMAKE_ARGS}"

# Configure, generate, and build
cmake ${CMAKE_ARGS}
cmake --build ${CAPLIB_BUILD_DIR} -- ${BUILD_TOOL_OPTIONS}
